apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:fTjE2FjzIth70eCy8FnA9qSKNV2Anty40j4VBSlR6nBvxFobvoFpwA==,iv:fFZ6KuCyR/v7a1JRtm0d04U59t3fPFFt9+3zQ6aDItk=,tag:s8TfH2UbWS8If9IXGghZEA==,type:str]
sops:
    age:
        - recipient: age127lfjxqr3t58rvn0x79cu6w3x0t9ztxw6rwctnrk7amhjpyja43s49vnnp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMm1zVG0vVUlGTEcrcWl1
            eVd4QUF4aVRvdlNER1p3Q0YzL1I1OEVlMG13CitwS24rQjhiTGpiL2JJdTRrWElR
            eWFmVjZpVllUZmdNaisxdWdIODZPaGMKLS0tIGcyMno4c0Jzd1NEUUJ3eTFaYlJy
            OWJyOGxIOEFYZ1VDQ2JWeFBMbU9OcTgKdShDE0tkGXMEQ5mgbzAA2TLEQVfEp2gP
            iyOuLbAKEXQ0IKW6/mNm2I8BZOObyAe3/MiwzQ4tx/FBmWWiwYm42Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T03:25:01Z"
    mac: ENC[AES256_GCM,data:xV/+cg1EB9WnRM9yEnsBzJJ7jW3HxCnlfVvF+i1fy6x9FS2BfrEzquxh/bopnlHfkB3Oy6Mvl7lAXn8m3bDis0DGj1uX9jxs2gwpDTIZZ3cIUJUOEU1YlzRxuB8dVjPeqKyUKX7oly/95FFByUIgg5EU3IVbKAi2hIhn+U+Wdv0=,iv:9K2Z86aIecejdQS8h3SjpMc0qK9F+AjoawIU4j/1m8I=,tag:V2FWxH0KAvB1gWoreiqOaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
